version: '3.8'

services:
  db:
    image: postgres:15
    container_name: rural_db
    restart: always
    environment:
      POSTGRES_DB: rural
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build: .
    container_name: rural_api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASS: password
      DB_NAME: rural
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  pgdata: